package com.example.todocompose.ui.theme.data.models

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.utils.Constants.DATABASE_TABLE

@Entity(tableName = DATABASE_TABLE)
data class ToDoTask(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0, //Default value, and auto generated by Room
    val title:String,
    val description : String,
    val priority : Priority
)
